# Shared fixtures for the panelio test suite.
# The helpers below are intentionally vectorized: no for / while loops.
# Every fixture respects the structural contract enforced by the package:
# label is a small grouping factor, is_intervention has a single monotone
# breakpoint, and each observation x time layer composition sums to one.

TEST_GROUP_LABELS <- c("ctrl", "treat")

make_test_elapsed_time <- \(time_point_count, elapsed_time_values = NULL) {
  if (!is.null(elapsed_time_values)) {
    return(as.numeric(elapsed_time_values))
  }
  as.numeric((seq_len(time_point_count) - 1L) * 7)
}

# Deterministic sparse compositions, so the fixtures never depend on the
# random seed. The result has dim (observation, feature, time) and every
# observation x time layer column sums to one.
make_test_composition_array <- \(
  observation_count,
  feature_count,
  time_point_count,
  nonzero_feature_count = NULL
) {
  value_array <- array(
    ((seq_len(observation_count * feature_count * time_point_count) * 7L) %% 97L) + 1,
    dim = c(observation_count, feature_count, time_point_count)
  )

  if (!is.null(nonzero_feature_count)) {
    # apply() places the length feature_count result in front of the margins, so
    # the rank array is (feature, observation, time) and needs a permute.
    feature_rank <- array(
      as.vector(apply(
        value_array,
        c(1L, 3L),
        \(feature_slice) rank(-feature_slice, ties.method = "first")
      )),
      dim = c(feature_count, observation_count, time_point_count)
    )
    value_array <- value_array * (aperm(feature_rank, c(2L, 1L, 3L)) <= nonzero_feature_count)
  }

  # sweep() broadcasts one statistic per observation x time layer.
  sweep(
    value_array,
    MARGIN = c(1L, 3L),
    STATS = apply(value_array, c(1L, 3L), sum),
    FUN = "/"
  )
}

# expand.grid varies the first factor fastest, so listing feature first
# reproduces the canonical time_identifier x observation x feature order
# with feature varying fastest inside one observation and time cell.
make_test_panel_table <- \(
  observation_count = 4L,
  feature_count = 4L,
  time_point_count = 3L,
  group_count = 2L,
  elapsed_time_values = NULL,
  intervention_time_index = NULL,
  nonzero_feature_count = NULL,
  label_values = NULL
) {
  observation_levels <- sprintf("sample_%0*d", 3L, seq_len(observation_count))
  feature_levels <- sprintf("feature_%0*d", 3L, seq_len(feature_count))
  time_levels <- sprintf("time_%0*d", 3L, seq_len(time_point_count))
  resolved_elapsed <- make_test_elapsed_time(time_point_count, elapsed_time_values)
  resolved_breakpoint <- if (is.null(intervention_time_index)) {
    time_point_count
  } else {
    as.integer(intervention_time_index)
  }
  resolved_label <- if (is.null(label_values)) {
    group_index <- ((seq_len(observation_count) - 1L) %% as.integer(group_count)) + 1L
    group_labels <- if (as.integer(group_count) <= length(TEST_GROUP_LABELS)) {
      TEST_GROUP_LABELS[seq_len(as.integer(group_count))]
    } else {
      sprintf("group_%02d", seq_len(as.integer(group_count)))
    }
    factor(group_labels[group_index], levels = group_labels)
  } else {
    label_values
  }

  panel_table <- expand.grid(
    feature = feature_levels,
    observation = observation_levels,
    time_identifier = time_levels,
    KEEP.OUT.ATTRS = FALSE,
    stringsAsFactors = FALSE
  )
  observation_index <- match(panel_table$observation, observation_levels)
  feature_index <- match(panel_table$feature, feature_levels)
  time_index <- match(panel_table$time_identifier, time_levels)
  composition_array <- make_test_composition_array(
    observation_count = observation_count,
    feature_count = feature_count,
    time_point_count = time_point_count,
    nonzero_feature_count = nonzero_feature_count
  )
  # Index the (observation, feature, time) array with one cbind matrix per row
  # instead of relying on the memory order of a three dimensional array.
  panel_table$abundance_value <- composition_array[
    cbind(observation_index, feature_index, time_index)
  ]
  panel_table$elapsed_time <- resolved_elapsed[time_index]
  panel_table$label <- resolved_label[observation_index]
  panel_table$is_intervention <- time_index >= resolved_breakpoint
  panel_table[, c(
    "observation",
    "time_identifier",
    "elapsed_time",
    "feature",
    "abundance_value",
    "label",
    "is_intervention"
  ), drop = FALSE]
}

make_reference_manifest_lines <- \() {
  c(
    "# manifest.txt machine-parsable",
    "# generated by panelio test suite",
    "[observation_meta]",
    "observation_id = sample_001; label = ctrl",
    "observation_id = sample_002; label = treat",
    "[time_meta]",
    paste0(
      "time_identifier = time_001; elapsed_time = 0; delta_t = 0; ",
      "is_intervention_timepoint = FALSE"
    ),
    paste0(
      "time_identifier = time_002; elapsed_time = 7; delta_t = 7; ",
      "is_intervention_timepoint = TRUE"
    ),
    "[file_index]",
    "time_001.csv",
    "time_002.csv"
  )
}

make_layer_table <- \(observation_levels, feature_levels, abundance_value) {
  cbind(
    data.frame(observation_id = observation_levels, stringsAsFactors = FALSE),
    as.data.frame(
      matrix(
        abundance_value,
        nrow = length(observation_levels),
        byrow = TRUE,
        dimnames = list(NULL, feature_levels)
      ),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  )
}

# Each observation row becomes a valid composition, which is what a stored
# layer table must contain: the feature columns of every row sum to one.
make_composition_block <- \(observation_levels, feature_levels, abundance_value) {
  block_table <- make_layer_table(observation_levels, feature_levels, abundance_value)
  feature_columns <- as.matrix(block_table[, feature_levels, drop = FALSE])
  block_table[, feature_levels] <- sweep(
    feature_columns,
    1L,
    rowSums(feature_columns),
    "/"
  )
  block_table
}

# Build a hand crafted archive (possibly malformed) to exercise the reader.
# Layer tables are supplied as a named list: names are the archive file names.
# The package writer is reused so that a hand built archive follows the same
# floating point precision contract as a generated one.
write_raw_archive <- \(manifest_lines, layer_tables, archive_path) {
  staging_dir <- tempfile("panelio_raw_")
  dir.create(staging_dir, recursive = TRUE, showWarnings = FALSE)
  on.exit(unlink(staging_dir, recursive = TRUE), add = TRUE)
  writeLines(manifest_lines, file.path(staging_dir, "manifest.txt"))
  file_paths <- file.path(staging_dir, names(layer_tables))
  write_flag <- vapply(
    seq_along(file_paths),
    \(file_index) {
      panelio:::write_csv_table(layer_tables[[file_index]], file_paths[file_index])
      TRUE
    },
    logical(1L)
  )
  stopifnot(all(write_flag))
  system2("tar", c("-czf", archive_path, "-C", staging_dir, "."))
  archive_path
}
